[package]
name = "mc2_fi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.1"
serde = { version = "1.0", features = ["derive"] }
tracing = "0.1.35"
hex = "0.4.3"
dashmap = "5.3.4"
tokio = { version = "1", features = ["full"] }
crossbeam = "*"
reqwest = { version = "*", default-features = false, features = [
	"rustls-tls",
	"serde_json",
	"json",
] }
tokio-tungstenite = { version = "*", features = [] }
itertools = "0.10.3"
futures = "*"
serde_json = "*"
peroxide = "*"
chrono = "*"
deadpool-postgres = "*"
tokio-cron-scheduler = "*"
model = { path = "src/model" }
gen = { path = "src/gen" }
lib = { path = "src/lib" }
bytes = "*"
web3 = { version = "0.18", features = ["signing"] }
secp256k1 = "0.21.3"
rand = "0.8.5"
ethabi = "18.0.0"
axum = { version = "0.6.18", default-features = false, features = [
	"http1",
	"json",
	"matched-path",
	"original-uri",
	"tokio",
] }
axum-server = { version = "0.5.0", features = ["tls-rustls"] }

deadpool = { version = "0.9.5", features = ["managed", "rt_tokio_1"] }
async-trait = "*"
crypto = { path = "src/cryptos/crypto" }
eth-sdk = { path = "src/cryptos/ethereum/eth-sdk" }
[dependencies.uuid]
version = "1.1.2"
features = [
	"v4",                # Lets you generate random UUIDs
	"fast-rng",          # Use a faster (but still sufficiently random) RNG
	"macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
	"serde",             # Enable serde support
]
[features]
default = []
no-github-ci-tests = []

[lib]
path = "src/service/lib.rs"

[[bin]]
name = "auth"
path = "src/service/auth/main.rs"

[[bin]]
name = "user"
path = "src/service/user/main.rs"

[[bin]]
name = "admin"
path = "src/service/admin/main.rs"

[[bin]]
name = "escrow-watcher"
path = "src/service/escrow_watcher/main.rs"

[[bin]]
name = "trade-watcher"
path = "src/service/trade_watcher/main.rs"

[workspace]
members = [
	"src/cryptos/ethereum/eth-sdk",
	"src/cryptos/crypto",
	"src/lib",
	"src/gen",
]