#[path = "../admin/endpoints.rs"]
pub mod admin_endpoints;
#[path = "../admin/method.rs"]
pub mod admin_method;
#[path = "../shared/audit/mod.rs"]
pub mod audit;
pub mod back_strategy;
pub mod endpoints;
pub mod method;
